{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pass-transfer.fullname" . }}-mysql
  labels:
    {{- include "pass-transfer.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  root-password: {{ .Values.database.mysql.auth.rootPassword | b64enc }}
  database: {{ .Values.database.mysql.auth.database | b64enc }}
  username: {{ .Values.database.mysql.auth.username | b64enc }}
  password: {{ .Values.database.mysql.auth.password | b64enc }}
{{- end }}
